version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:17-jdk

jobs:
  # Primer job: compilar el proyecto
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Compilar con Gradle
          command: ./gradlew build

  # Segundo job: correr las pruebas unitarias
  test:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Ejecutar pruebas unitarias
          command: ./gradlew test

  # Tercer job: chequeo de estilo de código
  lint:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Chequear estilo de código
          command: ./gradlew checkstyleMain

  # Cuarto job: compilación de imagen Docker
  build-docker:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Compilar imagen Docker
          command: docker build -t spring-petclinic .

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - test
      - build-docker:
          requires:
            - lint
